### ISSUE TITLE
Error on RightClick

### ISSUE THREAD

**Issue by x0Z3ro0x** [ipsk/CitizensCMD#10]
Just added the plugin, added all the commands, tested as OP and everything worked perfect. Then decided to test as a normal user. Got the no permissions error which then printed off an error.

Steps-to-issue:

/pex user x0Z3ro0x group add default
/pex user x0Z3ro0x group remove owner
/deop x0Z3ro0x
/spawn

Entered two portals undergoing one world change.

Right Clicked the NPC and was told I didn't have permission.

Errors began printing out.

```
[22:39:56 INFO]: x0Z3ro0x issued server command: /pex user x0Z3ro0x group add Miner
[22:39:56 WARN]: [PermissionsEx] User x0Z3ro0x tried to access chat command "pex user x0Z3ro0x group add Miner", but doesn't have permission to do this.
[22:39:56 ERROR]: Could not pass event NPCRightClickEvent to CitizensCMD v1.2.2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:414) [Citizens.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1580) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:69) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_171]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
        at com.triumphcraft.citizenscmd.listener.NPCListener.doCommands(NPCListener.java:183) ~[?:?]
        at com.triumphcraft.citizenscmd.listener.NPCListener.onRight(NPCListener.java:54) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        ... 24 more
```

Saves looks like this:

```
SavedNPCs:
  '8':
    cooldown: 3600
    customPerms: miner
    commands: pex user %p% group add Miner; pex user %p% group remove default; say
      WOOT! %p% has taken up the profession Miner!
```

I have also given the permission node citizenscmd.miner but I am unsure if that is correct. I am sure this issue is caused by me, but on the chance this is a genuine error, I have posted it here. Thank you for your time.

**Comment by MithrandirCraft** [comment]
Same error here.
