### ISSUE TITLE
Error Message in Colsole

### ISSUE THREAD

**Issue by Wichier** [ipsk/CitizensCMD#6]
My server is using the latest spigot-1.12.2 build, and always have some error messages about this plugin.

This will happen every time when enabling the server, check it:

`[14:08:13 INFO]: [CitizensCMD] Enabling CitizensCMD v1.2.0
[14:08:13 WARN]: java.lang.NullPointerException
[14:08:13 WARN]:        at com.triumphcraft.citizenscmd.utility.UpdateChecker.toReadable(UpdateChecker.java:57)
[14:08:13 WARN]:        at com.triumphcraft.citizenscmd.utility.UpdateChecker.checkHigher(UpdateChecker.java:27)
[14:08:13 WARN]:        at com.triumphcraft.citizenscmd.utility.UpdateChecker.checkUpdate(UpdateChecker.java:33)
[14:08:13 WARN]:        at com.triumphcraft.citizenscmd.utility.UpdateChecker.<init>(UpdateChecker.java:19)
[14:08:13 WARN]:        at com.triumphcraft.citizenscmd.listener.PlayerEvents.<init>(PlayerEvents.java:19)
[14:08:13 WARN]:        at com.triumphcraft.citizenscmd.CitizensCMD.registerEvents(CitizensCMD.java:41)
[14:08:13 WARN]:        at com.triumphcraft.citizenscmd.CitizensCMD.onEnable(CitizensCMD.java:24)
[14:08:13 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[14:08:13 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[14:08:13 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[14:08:13 WARN]:        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366)
[14:08:13 WARN]:        at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114)
[14:08:13 WARN]:        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
[14:08:13 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[14:08:13 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[14:08:13 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
[14:08:13 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:634)
[14:08:13 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:444)
[14:08:13 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:407)
[14:08:13 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[14:08:13 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[14:08:13 WARN]:        at java.lang.Thread.run(Thread.java:748)`

**Comment by Wichier** [comment]
This has been fixed in version 1.2.1, thanks a lot!
